//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarma.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Alarmass
    {
        [Display(Name = "#")]
        public int id { get; set; }
        [Display(Name = "Hora")]
        [DataType(DataType.Time)]
        public System.TimeSpan hora { get; set; }
        [Display(Name = "Evento")]
        public string nombre { get; set; }
        [Display(Name = "Dias a sonar")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.DateTime)]
        public System.DateTime diasSemana { get; set; }
        [Display(Name = "Activar o desactivar")]
        public bool Activar { get; set; }
    }
}
